language: node_js
node_js:
  - "node"

env:
  global:
    - URL_DEV: andrewsolovev-burberry-fake-shop-for-study-dev
    - URL_PROD: andrewsolovev-burberry-fake-shop-for-study
script:
  - npm run lint

before_deploy:
  - npm run build

deploy:
  # deploy develop to the staging environment
  - provider: script
    script: now alias $(now build -t=$NOW_TOKEN --public) $URL_DEV -t=$NOW_TOKEN
    on:
      branch: develop
  # deploy master to production
